version: '3.3'
services:
   db:
     image: store/oracle/database-enterprise:12.2.0.1	
     volumes:
       - data:/opt/oracle/oradata
     environment:
       -ORACLE_SID=C##COSME
       -ORACLE_PWD=1234
     ports:
       - 1521:1521
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat
    volumes:
            - ./target/ProjecteFinal.war:/usr/local/tomcat/webapps/ProjecteFinal.war
    ports:
      - '8082:8080'
    environment:
      -ORACLE_SID=C##COSME
      -ORACLE_PWD=1234
volumes:
    db_vol:      
